-- DELETE - DELETE IS USED TO DELETE THE RECORD.

-- NOTE.
-- 1. USE THE PRIMARY KEY TO DELETE THE RECORD.
-- 2. BE CAREFULL WHILE DELETING THE RECORD BECAUSE IF YOU
--  USE THE GENDER IT WILL DELETE ALL THE MATCHING RECORD.
-- 3. WHILE DELETING CHECK CARFULLY.

-- DELETE WITHOUT WHERE CLAUSE IT WILL DELETE ALL RECORDS.
DELETE FROM persons;

-- DELETE USING THE CONSTRAINT.
DELETE FROM persons WHERE id=1


-- INSERTING THE DELETED RECORD AGAIN.
insert into persons (id, first_name, last_name, email, gender, dob, country) values (1, 'Jere', 'Batt', 'jbatt0@zimbio.com', 'Male', '8/27/1995', 'Sweden');
