-- EXTRACT - using this we can extract the data from the date.

-- YEAR EXTRACTION

SELECT EXTRACT(YEAR FROM NOW());

-- MONTH EXTRACTION

SELECT EXTRACT(MONTH FROM NOW());

-- DATE.

SELECT EXTRACT(DAY FROM NOW())


-- DAY OF THE WEEK.

SELECT EXTRACT(DOW FROM NOW());

-- CENTURY

SELECT EXTRACT(CENTURY FROM NOW())