create table cars (
	id BIGINT NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price NUMERIC(19,2)
);

DROP TABLE cars


insert into cars (id, make, model, price) values (1, 'Ford', 'Econoline E350', 1112);
insert into cars (id, make, model, price) values (2, 'Hyundai', 'Accent', 1067);
insert into cars (id, make, model, price) values (3, 'Mazda', '626', 1147);
insert into cars (id, make, model, price) values (4, 'Mazda', 'MPV', 1071);
insert into cars (id, make, model, price) values (5, 'GMC', '2500', 1084);
insert into cars (id, make, model, price) values (6, 'Volvo', 'V50', 1161);
insert into cars (id, make, model, price) values (7, 'Nissan', 'JUKE', 1008);
insert into cars (id, make, model, price) values (8, 'Infiniti', 'J', 1047);
insert into cars (id, make, model, price) values (9, 'Maybach', 'Landaulet', 1038);
insert into cars (id, make, model, price) values (10, 'Mercedes-Benz', 'SLK-Class', 1022);
insert into cars (id, make, model, price) values (11, 'GMC', '2500 Club Coupe', 1083);
insert into cars (id, make, model, price) values (12, 'Cadillac', 'Escalade', 1178);
insert into cars (id, make, model, price) values (13, 'Ford', 'Thunderbird', 1065);
insert into cars (id, make, model, price) values (14, 'Buick', 'Riviera', 1062);
insert into cars (id, make, model, price) values (15, 'Mazda', '929', 1176);
insert into cars (id, make, model, price) values (16, 'Dodge', 'Caliber', 1119);
insert into cars (id, make, model, price) values (17, 'Ford', 'Aerostar', 1198);
insert into cars (id, make, model, price) values (18, 'Chrysler', 'Concorde', 1178);
insert into cars (id, make, model, price) values (19, 'Chevrolet', 'Suburban 2500', 1180);
insert into cars (id, make, model, price) values (20, 'Chevrolet', 'Astro', 1060);
insert into cars (id, make, model, price) values (21, 'Acura', 'Vigor', 1042);
insert into cars (id, make, model, price) values (22, 'Mazda', '929', 1061);
insert into cars (id, make, model, price) values (23, 'Ford', 'F250', 1043);
insert into cars (id, make, model, price) values (24, 'Toyota', 'Prius', 1058);
insert into cars (id, make, model, price) values (25, 'Subaru', 'Impreza', 1133);
insert into cars (id, make, model, price) values (26, 'Aston Martin', 'V8 Vantage', 1096);
insert into cars (id, make, model, price) values (27, 'Nissan', 'Murano', 1099);
insert into cars (id, make, model, price) values (28, 'Eagle', 'Summit', 1034);
insert into cars (id, make, model, price) values (29, 'Subaru', 'Legacy', 1174);
insert into cars (id, make, model, price) values (30, 'Chevrolet', 'Corvette', 1055);
insert into cars (id, make, model, price) values (31, 'Isuzu', 'i-290', 1191);
insert into cars (id, make, model, price) values (32, 'Nissan', 'Sentra', 1041);
insert into cars (id, make, model, price) values (33, 'Infiniti', 'FX', 1155);
insert into cars (id, make, model, price) values (34, 'Kia', 'Spectra', 1106);
insert into cars (id, make, model, price) values (35, 'Mitsubishi', 'Diamante', 1008);
insert into cars (id, make, model, price) values (36, 'Ford', 'E150', 1103);
insert into cars (id, make, model, price) values (37, 'BMW', '5 Series', 1132);
insert into cars (id, make, model, price) values (38, 'Chevrolet', 'Impala', 1101);
insert into cars (id, make, model, price) values (39, 'Chevrolet', 'Sportvan G20', 1015);
insert into cars (id, make, model, price) values (40, 'Isuzu', 'Rodeo', 1058);
insert into cars (id, make, model, price) values (41, 'Toyota', 'Truck Xtracab SR5', 1038);
insert into cars (id, make, model, price) values (42, 'Nissan', 'Cube', 1183);
insert into cars (id, make, model, price) values (43, 'Toyota', 'Land Cruiser', 1149);
insert into cars (id, make, model, price) values (44, 'Lamborghini', 'Murciélago', 1200);
insert into cars (id, make, model, price) values (45, 'Maserati', 'Spyder', 1060);
insert into cars (id, make, model, price) values (46, 'Mitsubishi', 'Montero Sport', 1025);
insert into cars (id, make, model, price) values (47, 'Pontiac', 'Grand Prix', 1114);
insert into cars (id, make, model, price) values (48, 'Oldsmobile', 'Silhouette', 1076);
insert into cars (id, make, model, price) values (49, 'Chevrolet', 'Express', 1178);
insert into cars (id, make, model, price) values (50, 'Land Rover', 'Range Rover', 1051);
insert into cars (id, make, model, price) values (51, 'Ford', 'Aspire', 1142);
insert into cars (id, make, model, price) values (52, 'Cadillac', 'Escalade ESV', 1151);
insert into cars (id, make, model, price) values (53, 'GMC', 'Envoy', 1099);
insert into cars (id, make, model, price) values (54, 'Dodge', 'Ram Van 1500', 1141);
insert into cars (id, make, model, price) values (55, 'Nissan', 'Altima', 1187);
insert into cars (id, make, model, price) values (56, 'Mercedes-Benz', 'SL-Class', 1146);
insert into cars (id, make, model, price) values (57, 'Maserati', 'GranTurismo', 1037);
insert into cars (id, make, model, price) values (58, 'Ford', 'Contour', 1046);
insert into cars (id, make, model, price) values (59, 'Jeep', 'Wrangler', 1146);
insert into cars (id, make, model, price) values (60, 'Volkswagen', 'Passat', 1178);
insert into cars (id, make, model, price) values (61, 'Chevrolet', 'Uplander', 1109);
insert into cars (id, make, model, price) values (62, 'Audi', 'Quattro', 1018);
insert into cars (id, make, model, price) values (63, 'Dodge', 'Ram Van 3500', 1154);
insert into cars (id, make, model, price) values (64, 'Saturn', 'Aura', 1131);
insert into cars (id, make, model, price) values (65, 'Toyota', 'Land Cruiser', 1036);
insert into cars (id, make, model, price) values (66, 'Land Rover', 'Range Rover', 1185);
insert into cars (id, make, model, price) values (67, 'Mercury', 'Grand Marquis', 1023);
insert into cars (id, make, model, price) values (68, 'Ford', 'Edge', 1040);
insert into cars (id, make, model, price) values (69, 'Pontiac', 'G6', 1076);
insert into cars (id, make, model, price) values (70, 'Mercedes-Benz', 'S-Class', 1133);
insert into cars (id, make, model, price) values (71, 'Infiniti', 'G', 1042);
insert into cars (id, make, model, price) values (72, 'Hyundai', 'Accent', 1043);
insert into cars (id, make, model, price) values (73, 'Kia', 'Sephia', 1190);
insert into cars (id, make, model, price) values (74, 'Mitsubishi', 'Pajero', 1190);
insert into cars (id, make, model, price) values (75, 'Volkswagen', 'Routan', 1167);
insert into cars (id, make, model, price) values (76, 'Infiniti', 'G37', 1048);
insert into cars (id, make, model, price) values (77, 'Infiniti', 'G35', 1083);
insert into cars (id, make, model, price) values (78, 'Bentley', 'Continental', 1185);
insert into cars (id, make, model, price) values (79, 'Pontiac', 'Grand Am', 1088);
insert into cars (id, make, model, price) values (80, 'Toyota', 'FJ Cruiser', 1008);
insert into cars (id, make, model, price) values (81, 'Volkswagen', 'Type 2', 1192);
insert into cars (id, make, model, price) values (82, 'Acura', 'Legend', 1145);
insert into cars (id, make, model, price) values (83, 'Volkswagen', 'Jetta III', 1171);
insert into cars (id, make, model, price) values (84, 'Mercedes-Benz', '500E', 1052);
insert into cars (id, make, model, price) values (85, 'Mitsubishi', 'Mirage', 1016);
insert into cars (id, make, model, price) values (86, 'Volkswagen', 'Golf', 1021);
insert into cars (id, make, model, price) values (87, 'Pontiac', 'Gemini', 1033);
insert into cars (id, make, model, price) values (88, 'Suzuki', 'Swift', 1177);
insert into cars (id, make, model, price) values (89, 'Mercedes-Benz', 'C-Class', 1070);
insert into cars (id, make, model, price) values (90, 'Saab', '9-5', 1026);
insert into cars (id, make, model, price) values (91, 'Ford', 'Ranger', 1003);
insert into cars (id, make, model, price) values (92, 'GMC', 'Canyon', 1084);
insert into cars (id, make, model, price) values (93, 'Isuzu', 'Amigo', 1179);
insert into cars (id, make, model, price) values (94, 'Chevrolet', 'Tahoe', 1101);
insert into cars (id, make, model, price) values (95, 'Audi', 'A6', 1133);
insert into cars (id, make, model, price) values (96, 'Kia', 'Carens', 1076);
insert into cars (id, make, model, price) values (97, 'Honda', 'CR-V', 1087);
insert into cars (id, make, model, price) values (98, 'Lexus', 'SC', 1132);
insert into cars (id, make, model, price) values (99, 'Ford', 'Windstar', 1078);
insert into cars (id, make, model, price) values (100, 'Chrysler', 'LHS', 1183);
insert into cars (id, make, model, price) values (101, 'Buick', 'Riviera', 1110);
insert into cars (id, make, model, price) values (102, 'Ford', 'Ranger', 1180);
insert into cars (id, make, model, price) values (103, 'Jeep', 'Grand Cherokee', 1184);
insert into cars (id, make, model, price) values (104, 'Audi', '4000s', 1049);
insert into cars (id, make, model, price) values (105, 'BMW', 'M3', 1136);
insert into cars (id, make, model, price) values (106, 'Mazda', 'Protege', 1196);
insert into cars (id, make, model, price) values (107, 'Audi', 'S6', 1189);
insert into cars (id, make, model, price) values (108, 'Chevrolet', 'Aveo', 1054);
insert into cars (id, make, model, price) values (109, 'Mitsubishi', 'Mirage', 1023);
insert into cars (id, make, model, price) values (110, 'Chevrolet', 'TrailBlazer', 1167);
insert into cars (id, make, model, price) values (111, 'Dodge', 'Ram Van 2500', 1189);
insert into cars (id, make, model, price) values (112, 'Toyota', 'MR2', 1150);
insert into cars (id, make, model, price) values (113, 'Pontiac', 'G3', 1119);
insert into cars (id, make, model, price) values (114, 'Subaru', 'Impreza', 1091);
insert into cars (id, make, model, price) values (115, 'Chevrolet', 'Tracker', 1135);
insert into cars (id, make, model, price) values (116, 'Lexus', 'SC', 1039);
insert into cars (id, make, model, price) values (117, 'Acura', 'TL', 1059);
insert into cars (id, make, model, price) values (118, 'Toyota', 'Sienna', 1041);
insert into cars (id, make, model, price) values (119, 'Plymouth', 'Fury', 1052);
insert into cars (id, make, model, price) values (120, 'Volkswagen', 'Passat', 1154);
insert into cars (id, make, model, price) values (121, 'Chevrolet', 'Metro', 1071);
insert into cars (id, make, model, price) values (122, 'GMC', 'Envoy', 1173);
insert into cars (id, make, model, price) values (123, 'Spyker', 'C8 Double 12 S', 1186);
insert into cars (id, make, model, price) values (124, 'Pontiac', 'Sunbird', 1037);
insert into cars (id, make, model, price) values (125, 'Infiniti', 'G', 1174);
insert into cars (id, make, model, price) values (126, 'Ford', 'Mustang', 1098);
insert into cars (id, make, model, price) values (127, 'Dodge', 'Stratus', 1173);
insert into cars (id, make, model, price) values (128, 'Mercury', 'Sable', 1071);
insert into cars (id, make, model, price) values (129, 'GMC', 'Safari', 1046);
insert into cars (id, make, model, price) values (130, 'Jeep', 'Cherokee', 1127);
insert into cars (id, make, model, price) values (131, 'Toyota', 'Celica', 1120);
insert into cars (id, make, model, price) values (132, 'Toyota', 'Venza', 1191);
insert into cars (id, make, model, price) values (133, 'Lincoln', 'Mark VIII', 1098);
insert into cars (id, make, model, price) values (134, 'Isuzu', 'Amigo', 1140);
insert into cars (id, make, model, price) values (135, 'GMC', 'Savana 1500', 1107);
insert into cars (id, make, model, price) values (136, 'Honda', 'Pilot', 1033);
insert into cars (id, make, model, price) values (137, 'Plymouth', 'Roadrunner', 1087);
insert into cars (id, make, model, price) values (138, 'Audi', 'A4', 1042);
insert into cars (id, make, model, price) values (139, 'GMC', 'Yukon', 1098);
insert into cars (id, make, model, price) values (140, 'Mercury', 'Sable', 1063);
insert into cars (id, make, model, price) values (141, 'Mazda', '626', 1129);
insert into cars (id, make, model, price) values (142, 'Mercedes-Benz', 'GL-Class', 1140);
insert into cars (id, make, model, price) values (143, 'Ford', 'F250', 1014);
insert into cars (id, make, model, price) values (144, 'Chevrolet', 'Cavalier', 1130);
insert into cars (id, make, model, price) values (145, 'Lexus', 'SC', 1080);
insert into cars (id, make, model, price) values (146, 'Mazda', 'RX-8', 1132);
insert into cars (id, make, model, price) values (147, 'Lincoln', 'Navigator', 1072);
insert into cars (id, make, model, price) values (148, 'Nissan', 'Frontier', 1111);
insert into cars (id, make, model, price) values (149, 'Ford', 'F-Series', 1146);
insert into cars (id, make, model, price) values (150, 'Infiniti', 'I', 1163);
insert into cars (id, make, model, price) values (151, 'Saab', '9000', 1001);
insert into cars (id, make, model, price) values (152, 'Honda', 'Accord', 1193);
insert into cars (id, make, model, price) values (153, 'Dodge', 'Durango', 1115);
insert into cars (id, make, model, price) values (154, 'Infiniti', 'G', 1012);
insert into cars (id, make, model, price) values (155, 'Chevrolet', 'Cavalier', 1034);
insert into cars (id, make, model, price) values (156, 'Toyota', 'Celica', 1082);
insert into cars (id, make, model, price) values (157, 'Ford', 'Thunderbird', 1031);
insert into cars (id, make, model, price) values (158, 'Dodge', 'Charger', 1066);
insert into cars (id, make, model, price) values (159, 'Mazda', 'MPV', 1124);
insert into cars (id, make, model, price) values (160, 'Hummer', 'H1', 1168);
insert into cars (id, make, model, price) values (161, 'Honda', 'Odyssey', 1005);
insert into cars (id, make, model, price) values (162, 'Nissan', '370Z', 1168);
insert into cars (id, make, model, price) values (163, 'Infiniti', 'G', 1194);
insert into cars (id, make, model, price) values (164, 'Chevrolet', 'Camaro', 1117);
insert into cars (id, make, model, price) values (165, 'Ford', 'Bronco', 1158);
insert into cars (id, make, model, price) values (166, 'Kia', 'Spectra', 1018);
insert into cars (id, make, model, price) values (167, 'Toyota', 'Previa', 1116);
insert into cars (id, make, model, price) values (168, 'Suzuki', 'Grand Vitara', 1112);
insert into cars (id, make, model, price) values (169, 'Hyundai', 'Entourage', 1086);
insert into cars (id, make, model, price) values (170, 'Kia', 'Rio', 1067);
insert into cars (id, make, model, price) values (171, 'Lincoln', 'LS', 1155);
insert into cars (id, make, model, price) values (172, 'Volkswagen', 'Eos', 1014);
insert into cars (id, make, model, price) values (173, 'Kia', 'Sedona', 1039);
insert into cars (id, make, model, price) values (174, 'Mercury', 'Grand Marquis', 1090);
insert into cars (id, make, model, price) values (175, 'Acura', 'RL', 1037);
insert into cars (id, make, model, price) values (176, 'Volkswagen', 'Jetta', 1004);
insert into cars (id, make, model, price) values (177, 'Nissan', 'Versa', 1121);
insert into cars (id, make, model, price) values (178, 'Chevrolet', 'Aveo', 1060);
insert into cars (id, make, model, price) values (179, 'Chrysler', 'Concorde', 1097);
insert into cars (id, make, model, price) values (180, 'Chevrolet', 'Cavalier', 1060);
insert into cars (id, make, model, price) values (181, 'GMC', 'Jimmy', 1142);
insert into cars (id, make, model, price) values (182, 'Honda', 'Civic', 1169);
insert into cars (id, make, model, price) values (183, 'Infiniti', 'G35', 1095);
insert into cars (id, make, model, price) values (184, 'Mercedes-Benz', 'SLS-Class', 1188);
insert into cars (id, make, model, price) values (185, 'Maybach', 'Landaulet', 1055);
insert into cars (id, make, model, price) values (186, 'Aston Martin', 'V8 Vantage', 1120);
insert into cars (id, make, model, price) values (187, 'Mercury', 'Capri', 1092);
insert into cars (id, make, model, price) values (188, 'Suzuki', 'Swift', 1124);
insert into cars (id, make, model, price) values (189, 'Maybach', '62', 1141);
insert into cars (id, make, model, price) values (190, 'Lincoln', 'Navigator', 1003);
insert into cars (id, make, model, price) values (191, 'Lexus', 'IS-F', 1134);
insert into cars (id, make, model, price) values (192, 'Buick', 'Regal', 1084);
insert into cars (id, make, model, price) values (193, 'Chevrolet', 'Avalanche 1500', 1181);
insert into cars (id, make, model, price) values (194, 'Chrysler', 'Sebring', 1080);
insert into cars (id, make, model, price) values (195, 'Buick', 'LeSabre', 1015);
insert into cars (id, make, model, price) values (196, 'Land Rover', 'Freelander', 1155);
insert into cars (id, make, model, price) values (197, 'Chevrolet', 'Malibu', 1091);
insert into cars (id, make, model, price) values (198, 'Chrysler', 'Concorde', 1155);
insert into cars (id, make, model, price) values (199, 'Saab', '9-5', 1058);
insert into cars (id, make, model, price) values (200, 'BMW', '530', 1111);
insert into cars (id, make, model, price) values (201, 'Toyota', 'Highlander', 1051);
insert into cars (id, make, model, price) values (202, 'Saab', '9-7X', 1124);
insert into cars (id, make, model, price) values (203, 'Acura', 'TL', 1168);
insert into cars (id, make, model, price) values (204, 'Chevrolet', 'Corvette', 1108);
insert into cars (id, make, model, price) values (205, 'Maserati', 'Biturbo', 1041);
insert into cars (id, make, model, price) values (206, 'Infiniti', 'QX', 1137);
insert into cars (id, make, model, price) values (207, 'Chevrolet', 'Malibu', 1101);
insert into cars (id, make, model, price) values (208, 'Buick', 'Regal', 1193);
insert into cars (id, make, model, price) values (209, 'Buick', 'Century', 1046);
insert into cars (id, make, model, price) values (210, 'Rolls-Royce', 'Phantom', 1004);
insert into cars (id, make, model, price) values (211, 'Aston Martin', 'Vanquish S', 1143);
insert into cars (id, make, model, price) values (212, 'Chevrolet', 'Express 3500', 1020);
insert into cars (id, make, model, price) values (213, 'Chrysler', 'Pacifica', 1112);
insert into cars (id, make, model, price) values (214, 'Ford', 'Crown Victoria', 1195);
insert into cars (id, make, model, price) values (215, 'Mazda', '626', 1014);
insert into cars (id, make, model, price) values (216, 'Dodge', 'Challenger', 1005);
insert into cars (id, make, model, price) values (217, 'Chrysler', 'Concorde', 1197);
insert into cars (id, make, model, price) values (218, 'Lincoln', 'Mark VII', 1198);
insert into cars (id, make, model, price) values (219, 'Lincoln', 'MKS', 1110);
insert into cars (id, make, model, price) values (220, 'Lincoln', 'Continental', 1071);
insert into cars (id, make, model, price) values (221, 'Dodge', 'Ram Van B250', 1022);
insert into cars (id, make, model, price) values (222, 'Pontiac', 'Grand Prix', 1012);
insert into cars (id, make, model, price) values (223, 'Porsche', '911', 1038);
insert into cars (id, make, model, price) values (224, 'Saturn', 'S-Series', 1138);
insert into cars (id, make, model, price) values (225, 'Subaru', 'Legacy', 1000);
insert into cars (id, make, model, price) values (226, 'Jeep', 'Wrangler', 1029);
insert into cars (id, make, model, price) values (227, 'Lincoln', 'Town Car', 1111);
insert into cars (id, make, model, price) values (228, 'Plymouth', 'Voyager', 1174);
insert into cars (id, make, model, price) values (229, 'Buick', 'Century', 1075);
insert into cars (id, make, model, price) values (230, 'Ford', 'Tempo', 1089);
insert into cars (id, make, model, price) values (231, 'Mercedes-Benz', 'SLK-Class', 1112);
insert into cars (id, make, model, price) values (232, 'Chevrolet', 'Express 1500', 1081);
insert into cars (id, make, model, price) values (233, 'Mazda', 'B-Series', 1149);
insert into cars (id, make, model, price) values (234, 'Nissan', 'Pathfinder', 1148);
insert into cars (id, make, model, price) values (235, 'Suzuki', 'Forenza', 1082);
insert into cars (id, make, model, price) values (236, 'BMW', 'Z3', 1192);
insert into cars (id, make, model, price) values (237, 'Chevrolet', 'Classic', 1178);
insert into cars (id, make, model, price) values (238, 'Kia', 'Sorento', 1128);
insert into cars (id, make, model, price) values (239, 'Lexus', 'SC', 1090);
insert into cars (id, make, model, price) values (240, 'Lexus', 'GS', 1050);
insert into cars (id, make, model, price) values (241, 'Infiniti', 'Q', 1137);
insert into cars (id, make, model, price) values (242, 'Subaru', 'Legacy', 1018);
insert into cars (id, make, model, price) values (243, 'Mercedes-Benz', 'SLR McLaren', 1049);
insert into cars (id, make, model, price) values (244, 'Suzuki', 'SJ', 1197);
insert into cars (id, make, model, price) values (245, 'Mitsubishi', 'Chariot', 1167);
insert into cars (id, make, model, price) values (246, 'Mitsubishi', 'L300', 1124);
insert into cars (id, make, model, price) values (247, 'Pontiac', 'Grand Prix', 1152);
insert into cars (id, make, model, price) values (248, 'Ferrari', '430 Scuderia', 1181);
insert into cars (id, make, model, price) values (249, 'Honda', 'Odyssey', 1123);
insert into cars (id, make, model, price) values (250, 'Scion', 'tC', 1089);
insert into cars (id, make, model, price) values (251, 'Cadillac', 'SRX', 1186);
insert into cars (id, make, model, price) values (252, 'BMW', 'Z4', 1186);
insert into cars (id, make, model, price) values (253, 'BMW', 'M3', 1065);
insert into cars (id, make, model, price) values (254, 'Ford', 'Club Wagon', 1062);
insert into cars (id, make, model, price) values (255, 'Audi', 'A6', 1192);
insert into cars (id, make, model, price) values (256, 'Shelby', 'GT350', 1151);
insert into cars (id, make, model, price) values (257, 'Eagle', 'Talon', 1137);
insert into cars (id, make, model, price) values (258, 'Chrysler', 'LeBaron', 1069);
insert into cars (id, make, model, price) values (259, 'Toyota', 'RAV4', 1053);
insert into cars (id, make, model, price) values (260, 'Audi', 'Q7', 1107);
insert into cars (id, make, model, price) values (261, 'Buick', 'Regal', 1007);
insert into cars (id, make, model, price) values (262, 'Pontiac', 'Firebird', 1116);
insert into cars (id, make, model, price) values (263, 'Nissan', 'Sentra', 1142);
insert into cars (id, make, model, price) values (264, 'Pontiac', 'Firebird', 1186);
insert into cars (id, make, model, price) values (265, 'Chevrolet', 'Camaro', 1055);
insert into cars (id, make, model, price) values (266, 'Lexus', 'GS', 1010);
insert into cars (id, make, model, price) values (267, 'Honda', 'Civic', 1144);
insert into cars (id, make, model, price) values (268, 'Chevrolet', 'G-Series G20', 1142);
insert into cars (id, make, model, price) values (269, 'Pontiac', 'Parisienne', 1192);
insert into cars (id, make, model, price) values (270, 'GMC', 'Envoy', 1155);
insert into cars (id, make, model, price) values (271, 'Suzuki', 'Esteem', 1093);
insert into cars (id, make, model, price) values (272, 'Cadillac', 'Seville', 1138);
insert into cars (id, make, model, price) values (273, 'Maserati', 'Quattroporte', 1040);
insert into cars (id, make, model, price) values (274, 'Chevrolet', 'Cobalt', 1160);
insert into cars (id, make, model, price) values (275, 'Nissan', 'Sentra', 1175);
insert into cars (id, make, model, price) values (276, 'Rolls-Royce', 'Phantom', 1151);
insert into cars (id, make, model, price) values (277, 'Mercedes-Benz', 'S-Class', 1190);
insert into cars (id, make, model, price) values (278, 'Dodge', 'Caliber', 1082);
insert into cars (id, make, model, price) values (279, 'Lamborghini', 'Diablo', 1005);
insert into cars (id, make, model, price) values (280, 'Pontiac', 'Bonneville', 1094);
insert into cars (id, make, model, price) values (281, 'Cadillac', 'DeVille', 1134);
insert into cars (id, make, model, price) values (282, 'Pontiac', 'Sunbird', 1089);
insert into cars (id, make, model, price) values (283, 'Maybach', '57', 1003);
insert into cars (id, make, model, price) values (284, 'Mitsubishi', 'Challenger', 1043);
insert into cars (id, make, model, price) values (285, 'Suzuki', 'Sidekick', 1083);
insert into cars (id, make, model, price) values (286, 'Oldsmobile', 'Alero', 1126);
insert into cars (id, make, model, price) values (287, 'Bentley', 'Continental', 1025);
insert into cars (id, make, model, price) values (288, 'Toyota', 'Prius', 1067);
insert into cars (id, make, model, price) values (289, 'Chevrolet', 'Corvette', 1014);
insert into cars (id, make, model, price) values (290, 'Audi', 'Quattro', 1145);
insert into cars (id, make, model, price) values (291, 'Lincoln', 'LS', 1063);
insert into cars (id, make, model, price) values (292, 'Bentley', 'Continental GTC', 1029);
insert into cars (id, make, model, price) values (293, 'Ford', 'Fusion', 1138);
insert into cars (id, make, model, price) values (294, 'Mercedes-Benz', 'SLR McLaren', 1137);
insert into cars (id, make, model, price) values (295, 'Plymouth', 'Grand Voyager', 1083);
insert into cars (id, make, model, price) values (296, 'Cadillac', 'XLR', 1089);
insert into cars (id, make, model, price) values (297, 'GMC', 'Vandura 2500', 1019);
insert into cars (id, make, model, price) values (298, 'Mazda', 'RX-8', 1158);
insert into cars (id, make, model, price) values (299, 'Volvo', 'S80', 1088);
insert into cars (id, make, model, price) values (300, 'Land Rover', 'Defender', 1054);
insert into cars (id, make, model, price) values (301, 'Pontiac', 'Grand Am', 1072);
insert into cars (id, make, model, price) values (302, 'Aston Martin', 'DBS', 1046);
insert into cars (id, make, model, price) values (303, 'Toyota', 'Prius c', 1196);
insert into cars (id, make, model, price) values (304, 'Dodge', 'D350 Club', 1130);
insert into cars (id, make, model, price) values (305, 'Dodge', 'Magnum', 1122);
insert into cars (id, make, model, price) values (306, 'Audi', 'Q7', 1081);
insert into cars (id, make, model, price) values (307, 'Honda', 'Insight', 1122);
insert into cars (id, make, model, price) values (308, 'Maserati', 'Quattroporte', 1134);
insert into cars (id, make, model, price) values (309, 'Ford', 'Thunderbird', 1031);
insert into cars (id, make, model, price) values (310, 'BMW', '3 Series', 1059);
insert into cars (id, make, model, price) values (311, 'GMC', 'Yukon XL 1500', 1015);
insert into cars (id, make, model, price) values (312, 'Toyota', 'Camry', 1117);
insert into cars (id, make, model, price) values (313, 'Ford', 'Bronco II', 1107);
insert into cars (id, make, model, price) values (314, 'Subaru', 'Legacy', 1145);
insert into cars (id, make, model, price) values (315, 'Volkswagen', 'rio', 1146);
insert into cars (id, make, model, price) values (316, 'Infiniti', 'QX', 1104);
insert into cars (id, make, model, price) values (317, 'Jaguar', 'X-Type', 1152);
insert into cars (id, make, model, price) values (318, 'Porsche', 'Carrera GT', 1048);
insert into cars (id, make, model, price) values (319, 'Subaru', 'SVX', 1017);
insert into cars (id, make, model, price) values (320, 'Ford', 'F-Series', 1156);
insert into cars (id, make, model, price) values (321, 'Chevrolet', 'Tahoe', 1180);
insert into cars (id, make, model, price) values (322, 'Cadillac', 'Escalade EXT', 1006);
insert into cars (id, make, model, price) values (323, 'Chrysler', 'Crossfire', 1151);
insert into cars (id, make, model, price) values (324, 'BMW', 'M3', 1055);
insert into cars (id, make, model, price) values (325, 'Land Rover', 'Discovery', 1011);
insert into cars (id, make, model, price) values (326, 'Ford', 'Mustang', 1038);
insert into cars (id, make, model, price) values (327, 'Mazda', 'Mazdaspeed6', 1023);
insert into cars (id, make, model, price) values (328, 'Oldsmobile', 'Alero', 1150);
insert into cars (id, make, model, price) values (329, 'Chrysler', '300', 1041);
insert into cars (id, make, model, price) values (330, 'Honda', 'Civic', 1140);
insert into cars (id, make, model, price) values (331, 'Nissan', 'Pathfinder', 1176);
insert into cars (id, make, model, price) values (332, 'Jaguar', 'XK', 1097);
insert into cars (id, make, model, price) values (333, 'Toyota', 'Tacoma', 1023);
insert into cars (id, make, model, price) values (334, 'Dodge', 'Dakota Club', 1022);
insert into cars (id, make, model, price) values (335, 'Ford', 'F-Series', 1136);
insert into cars (id, make, model, price) values (336, 'Jeep', 'Grand Cherokee', 1105);
insert into cars (id, make, model, price) values (337, 'Nissan', 'Sentra', 1065);
insert into cars (id, make, model, price) values (338, 'Audi', 'A6', 1056);
insert into cars (id, make, model, price) values (339, 'Hummer', 'H2', 1167);
insert into cars (id, make, model, price) values (340, 'GMC', '1500', 1136);
insert into cars (id, make, model, price) values (341, 'Ford', 'Focus', 1131);
insert into cars (id, make, model, price) values (342, 'Mitsubishi', '3000GT', 1078);
insert into cars (id, make, model, price) values (343, 'Dodge', 'Dakota', 1177);
insert into cars (id, make, model, price) values (344, 'Suzuki', 'Grand Vitara', 1178);
insert into cars (id, make, model, price) values (345, 'Buick', 'Regal', 1084);
insert into cars (id, make, model, price) values (346, 'GMC', 'Sierra 1500', 1063);
insert into cars (id, make, model, price) values (347, 'Hummer', 'H2', 1044);
insert into cars (id, make, model, price) values (348, 'Mitsubishi', 'Galant', 1141);
insert into cars (id, make, model, price) values (349, 'Mercedes-Benz', 'GL-Class', 1146);
insert into cars (id, make, model, price) values (350, 'Mazda', 'MX-3', 1008);
insert into cars (id, make, model, price) values (351, 'Geo', 'Prizm', 1113);
insert into cars (id, make, model, price) values (352, 'Volkswagen', 'Eurovan', 1175);
insert into cars (id, make, model, price) values (353, 'GMC', 'Sierra 1500', 1146);
insert into cars (id, make, model, price) values (354, 'Volvo', 'S90', 1046);
insert into cars (id, make, model, price) values (355, 'Mitsubishi', 'Outlander', 1131);
insert into cars (id, make, model, price) values (356, 'Chevrolet', 'Volt', 1189);
insert into cars (id, make, model, price) values (357, 'Buick', 'Reatta', 1029);
insert into cars (id, make, model, price) values (358, 'Honda', 'S2000', 1069);
insert into cars (id, make, model, price) values (359, 'Chevrolet', 'Silverado 1500', 1086);
insert into cars (id, make, model, price) values (360, 'Plymouth', 'Sundance', 1076);
insert into cars (id, make, model, price) values (361, 'BMW', '325', 1141);
insert into cars (id, make, model, price) values (362, 'Volkswagen', 'Cabriolet', 1004);
insert into cars (id, make, model, price) values (363, 'GMC', 'Suburban 2500', 1003);
insert into cars (id, make, model, price) values (364, 'Subaru', 'Leone', 1011);
insert into cars (id, make, model, price) values (365, 'Mitsubishi', 'Galant', 1061);
insert into cars (id, make, model, price) values (366, 'Ford', 'Crown Victoria', 1161);
insert into cars (id, make, model, price) values (367, 'Ford', 'Freestar', 1153);
insert into cars (id, make, model, price) values (368, 'Buick', 'Roadmaster', 1038);
insert into cars (id, make, model, price) values (369, 'Dodge', 'Grand Caravan', 1028);
insert into cars (id, make, model, price) values (370, 'Mitsubishi', 'Precis', 1172);
insert into cars (id, make, model, price) values (371, 'Toyota', 'Echo', 1066);
insert into cars (id, make, model, price) values (372, 'Nissan', 'Pathfinder', 1132);
insert into cars (id, make, model, price) values (373, 'Mazda', 'RX-8', 1029);
insert into cars (id, make, model, price) values (374, 'Pontiac', 'Sunfire', 1102);
insert into cars (id, make, model, price) values (375, 'Toyota', '4Runner', 1016);
insert into cars (id, make, model, price) values (376, 'BMW', 'Z4', 1100);
insert into cars (id, make, model, price) values (377, 'Plymouth', 'Colt Vista', 1055);
insert into cars (id, make, model, price) values (378, 'Saab', '9-4X', 1151);
insert into cars (id, make, model, price) values (379, 'Suzuki', 'SJ', 1035);
insert into cars (id, make, model, price) values (380, 'Maserati', 'Quattroporte', 1107);
insert into cars (id, make, model, price) values (381, 'Mitsubishi', 'Mirage', 1022);
insert into cars (id, make, model, price) values (382, 'Ford', 'Explorer Sport', 1017);
insert into cars (id, make, model, price) values (383, 'Isuzu', 'i-290', 1186);
insert into cars (id, make, model, price) values (384, 'Mercedes-Benz', 'E-Class', 1156);
insert into cars (id, make, model, price) values (385, 'Cadillac', 'DeVille', 1043);
insert into cars (id, make, model, price) values (386, 'Cadillac', 'CTS-V', 1139);
insert into cars (id, make, model, price) values (387, 'Volkswagen', 'Jetta', 1067);
insert into cars (id, make, model, price) values (388, 'Ford', 'Econoline E150', 1167);
insert into cars (id, make, model, price) values (389, 'Chevrolet', 'Silverado 1500', 1162);
insert into cars (id, make, model, price) values (390, 'Cadillac', 'DeVille', 1193);
insert into cars (id, make, model, price) values (391, 'Geo', 'Metro', 1055);
insert into cars (id, make, model, price) values (392, 'Mercedes-Benz', '300SE', 1116);
insert into cars (id, make, model, price) values (393, 'GMC', 'Suburban 2500', 1188);
insert into cars (id, make, model, price) values (394, 'Toyota', 'Previa', 1069);
insert into cars (id, make, model, price) values (395, 'Chrysler', 'LHS', 1128);
insert into cars (id, make, model, price) values (396, 'Lexus', 'IS', 1075);
insert into cars (id, make, model, price) values (397, 'Lexus', 'GS', 1091);
insert into cars (id, make, model, price) values (398, 'Ford', 'Flex', 1177);
insert into cars (id, make, model, price) values (399, 'Toyota', 'RAV4', 1124);
insert into cars (id, make, model, price) values (400, 'Volkswagen', 'Passat', 1128);
insert into cars (id, make, model, price) values (401, 'Pontiac', 'Vibe', 1169);
insert into cars (id, make, model, price) values (402, 'Subaru', 'Loyale', 1200);
insert into cars (id, make, model, price) values (403, 'Mitsubishi', 'Chariot', 1094);
insert into cars (id, make, model, price) values (404, 'Pontiac', 'Firebird', 1029);
insert into cars (id, make, model, price) values (405, 'Toyota', 'Corolla', 1048);
insert into cars (id, make, model, price) values (406, 'Mazda', 'Mazda6', 1031);
insert into cars (id, make, model, price) values (407, 'Mitsubishi', 'Galant', 1137);
insert into cars (id, make, model, price) values (408, 'Land Rover', 'Discovery', 1022);
insert into cars (id, make, model, price) values (409, 'Toyota', 'Tacoma', 1089);
insert into cars (id, make, model, price) values (410, 'Toyota', 'Venza', 1086);
insert into cars (id, make, model, price) values (411, 'Audi', '90', 1098);
insert into cars (id, make, model, price) values (412, 'Toyota', 'Sequoia', 1115);
insert into cars (id, make, model, price) values (413, 'BMW', 'M6', 1200);
insert into cars (id, make, model, price) values (414, 'Chevrolet', 'G-Series 2500', 1114);
insert into cars (id, make, model, price) values (415, 'Volvo', 'V50', 1178);
insert into cars (id, make, model, price) values (416, 'Chevrolet', 'Blazer', 1002);
insert into cars (id, make, model, price) values (417, 'Lexus', 'LX', 1150);
insert into cars (id, make, model, price) values (418, 'Ferrari', 'F430', 1143);
insert into cars (id, make, model, price) values (419, 'Mazda', 'MPV', 1102);
insert into cars (id, make, model, price) values (420, 'Buick', 'Regal', 1132);
insert into cars (id, make, model, price) values (421, 'Toyota', '4Runner', 1147);
insert into cars (id, make, model, price) values (422, 'Buick', 'Regal', 1066);
insert into cars (id, make, model, price) values (423, 'Kia', 'Sportage', 1110);
insert into cars (id, make, model, price) values (424, 'Subaru', 'Tribeca', 1101);
insert into cars (id, make, model, price) values (425, 'Lexus', 'RX Hybrid', 1166);
insert into cars (id, make, model, price) values (426, 'Volvo', 'C70', 1057);
insert into cars (id, make, model, price) values (427, 'Mazda', 'B-Series Plus', 1187);
insert into cars (id, make, model, price) values (428, 'Mitsubishi', 'Outlander', 1066);
insert into cars (id, make, model, price) values (429, 'Mazda', 'MX-6', 1104);
insert into cars (id, make, model, price) values (430, 'Mercedes-Benz', 'SL-Class', 1064);
insert into cars (id, make, model, price) values (431, 'Chevrolet', 'Silverado 1500', 1077);
insert into cars (id, make, model, price) values (432, 'BMW', 'X3', 1038);
insert into cars (id, make, model, price) values (433, 'Pontiac', 'GTO', 1065);
insert into cars (id, make, model, price) values (434, 'Audi', 'S4', 1019);
insert into cars (id, make, model, price) values (435, 'Dodge', 'Ram 1500', 1033);
insert into cars (id, make, model, price) values (436, 'Nissan', 'Maxima', 1160);
insert into cars (id, make, model, price) values (437, 'Dodge', 'Caravan', 1069);
insert into cars (id, make, model, price) values (438, 'Chrysler', 'Sebring', 1186);
insert into cars (id, make, model, price) values (439, 'Lincoln', 'Navigator', 1051);
insert into cars (id, make, model, price) values (440, 'Buick', 'Reatta', 1086);
insert into cars (id, make, model, price) values (441, 'Kia', 'Optima', 1105);
insert into cars (id, make, model, price) values (442, 'Mitsubishi', 'Precis', 1066);
insert into cars (id, make, model, price) values (443, 'GMC', 'Savana 2500', 1093);
insert into cars (id, make, model, price) values (444, 'Mitsubishi', 'Space', 1065);
insert into cars (id, make, model, price) values (445, 'Toyota', 'Tacoma', 1170);
insert into cars (id, make, model, price) values (446, 'GMC', 'Sonoma', 1147);
insert into cars (id, make, model, price) values (447, 'Chevrolet', 'Blazer', 1184);
insert into cars (id, make, model, price) values (448, 'Ford', 'Flex', 1145);
insert into cars (id, make, model, price) values (449, 'Suzuki', 'Equator', 1046);
insert into cars (id, make, model, price) values (450, 'Jeep', 'Wrangler', 1120);
insert into cars (id, make, model, price) values (451, 'GMC', '1500 Club Coupe', 1168);
insert into cars (id, make, model, price) values (452, 'Ford', 'Crown Victoria', 1199);
insert into cars (id, make, model, price) values (453, 'Porsche', '944', 1120);
insert into cars (id, make, model, price) values (454, 'Volvo', 'XC90', 1070);
insert into cars (id, make, model, price) values (455, 'Subaru', 'Tribeca', 1183);
insert into cars (id, make, model, price) values (456, 'Lamborghini', 'Murciélago', 1037);
insert into cars (id, make, model, price) values (457, 'Toyota', 'RAV4', 1104);
insert into cars (id, make, model, price) values (458, 'Dodge', 'Grand Caravan', 1019);
insert into cars (id, make, model, price) values (459, 'Land Rover', 'Discovery', 1186);
insert into cars (id, make, model, price) values (460, 'BMW', '7 Series', 1134);
insert into cars (id, make, model, price) values (461, 'Ford', 'Festiva', 1087);
insert into cars (id, make, model, price) values (462, 'Mazda', 'Mazda3', 1177);
insert into cars (id, make, model, price) values (463, 'Suzuki', 'Esteem', 1006);
insert into cars (id, make, model, price) values (464, 'Volkswagen', 'New Beetle', 1135);
insert into cars (id, make, model, price) values (465, 'Toyota', 'T100 Xtra', 1045);
insert into cars (id, make, model, price) values (466, 'Scion', 'xD', 1090);
insert into cars (id, make, model, price) values (467, 'Hyundai', 'Elantra', 1017);
insert into cars (id, make, model, price) values (468, 'Volvo', '960', 1044);
insert into cars (id, make, model, price) values (469, 'Dodge', 'Caravan', 1152);
insert into cars (id, make, model, price) values (470, 'Nissan', 'Altima', 1175);
insert into cars (id, make, model, price) values (471, 'Toyota', 'T100', 1183);
insert into cars (id, make, model, price) values (472, 'Isuzu', 'Axiom', 1020);
insert into cars (id, make, model, price) values (473, 'Dodge', 'Ram 2500 Club', 1069);
insert into cars (id, make, model, price) values (474, 'Volkswagen', 'rio', 1156);
insert into cars (id, make, model, price) values (475, 'Dodge', 'Challenger', 1091);
insert into cars (id, make, model, price) values (476, 'Chevrolet', 'Caprice Classic', 1057);
insert into cars (id, make, model, price) values (477, 'GMC', 'Yukon XL 1500', 1036);
insert into cars (id, make, model, price) values (478, 'Audi', 'Q5', 1031);
insert into cars (id, make, model, price) values (479, 'Toyota', 'Sequoia', 1171);
insert into cars (id, make, model, price) values (480, 'Oldsmobile', 'Silhouette', 1092);
insert into cars (id, make, model, price) values (481, 'Oldsmobile', 'Bravada', 1100);
insert into cars (id, make, model, price) values (482, 'Saab', '9-3', 1177);
insert into cars (id, make, model, price) values (483, 'Chevrolet', 'Blazer', 1049);
insert into cars (id, make, model, price) values (484, 'Saab', '9-5', 1195);
insert into cars (id, make, model, price) values (485, 'Subaru', 'Legacy', 1037);
insert into cars (id, make, model, price) values (486, 'Pontiac', 'Grand Am', 1097);
insert into cars (id, make, model, price) values (487, 'Buick', 'Lucerne', 1012);
insert into cars (id, make, model, price) values (488, 'Acura', 'MDX', 1187);
insert into cars (id, make, model, price) values (489, 'Scion', 'xA', 1171);
insert into cars (id, make, model, price) values (490, 'Ford', 'F250', 1197);
insert into cars (id, make, model, price) values (491, 'Mercedes-Benz', 'CLK-Class', 1199);
insert into cars (id, make, model, price) values (492, 'Audi', 'A8', 1182);
insert into cars (id, make, model, price) values (493, 'Dodge', 'Caravan', 1144);
insert into cars (id, make, model, price) values (494, 'Audi', 'A6', 1121);
insert into cars (id, make, model, price) values (495, 'Acura', 'NSX', 1165);
insert into cars (id, make, model, price) values (496, 'Mazda', 'MX-5', 1112);
insert into cars (id, make, model, price) values (497, 'Aston Martin', 'V8 Vantage', 1019);
insert into cars (id, make, model, price) values (498, 'Land Rover', 'Range Rover Sport', 1125);
insert into cars (id, make, model, price) values (499, 'Mercury', 'Grand Marquis', 1105);
insert into cars (id, make, model, price) values (500, 'Nissan', '370Z', 1006);
insert into cars (id, make, model, price) values (501, 'Bentley', 'Continental', 1080);
insert into cars (id, make, model, price) values (502, 'Dodge', 'Neon', 1170);
insert into cars (id, make, model, price) values (503, 'Suzuki', 'Vitara', 1031);
insert into cars (id, make, model, price) values (504, 'Ram', '2500', 1131);
insert into cars (id, make, model, price) values (505, 'Kia', 'Optima', 1025);
insert into cars (id, make, model, price) values (506, 'Chevrolet', '2500', 1149);
insert into cars (id, make, model, price) values (507, 'Mercedes-Benz', 'G-Class', 1041);
insert into cars (id, make, model, price) values (508, 'Nissan', 'NX', 1109);
insert into cars (id, make, model, price) values (509, 'Land Rover', 'Discovery', 1007);
insert into cars (id, make, model, price) values (510, 'Alfa Romeo', 'Spider', 1142);
insert into cars (id, make, model, price) values (511, 'Lotus', 'Esprit', 1162);
insert into cars (id, make, model, price) values (512, 'Buick', 'Riviera', 1067);
insert into cars (id, make, model, price) values (513, 'Scion', 'xA', 1005);
insert into cars (id, make, model, price) values (514, 'GMC', '2500', 1189);
insert into cars (id, make, model, price) values (515, 'Pontiac', 'G6', 1143);
insert into cars (id, make, model, price) values (516, 'Honda', 'Odyssey', 1060);
insert into cars (id, make, model, price) values (517, 'Audi', 'Coupe GT', 1088);
insert into cars (id, make, model, price) values (518, 'Buick', 'Regal', 1061);
insert into cars (id, make, model, price) values (519, 'Chevrolet', 'HHR', 1158);
insert into cars (id, make, model, price) values (520, 'GMC', '1500', 1147);
insert into cars (id, make, model, price) values (521, 'Isuzu', 'Trooper', 1142);
insert into cars (id, make, model, price) values (522, 'Pontiac', 'Vibe', 1074);
insert into cars (id, make, model, price) values (523, 'Bentley', 'Continental', 1055);
insert into cars (id, make, model, price) values (524, 'Volkswagen', 'GTI', 1198);
insert into cars (id, make, model, price) values (525, 'Dodge', 'Dakota', 1196);
insert into cars (id, make, model, price) values (526, 'Mercedes-Benz', 'Sprinter 3500', 1157);
insert into cars (id, make, model, price) values (527, 'Toyota', 'Corolla', 1031);
insert into cars (id, make, model, price) values (528, 'Mazda', 'Mazda6', 1067);
insert into cars (id, make, model, price) values (529, 'Lexus', 'ES', 1040);
insert into cars (id, make, model, price) values (530, 'Chrysler', '300', 1016);
insert into cars (id, make, model, price) values (531, 'Chevrolet', 'Impala', 1055);
insert into cars (id, make, model, price) values (532, 'Toyota', 'Celica', 1096);
insert into cars (id, make, model, price) values (533, 'Lamborghini', 'Murciélago', 1012);
insert into cars (id, make, model, price) values (534, 'Buick', 'Regal', 1146);
insert into cars (id, make, model, price) values (535, 'Mercedes-Benz', 'GLK-Class', 1166);
insert into cars (id, make, model, price) values (536, 'Oldsmobile', 'Intrigue', 1043);
insert into cars (id, make, model, price) values (537, 'GMC', '3500 Club Coupe', 1133);
insert into cars (id, make, model, price) values (538, 'Lincoln', 'Navigator L', 1025);
insert into cars (id, make, model, price) values (539, 'Mazda', 'Familia', 1130);
insert into cars (id, make, model, price) values (540, 'Hyundai', 'Santa Fe', 1183);
insert into cars (id, make, model, price) values (541, 'Chevrolet', 'Sonic', 1134);
insert into cars (id, make, model, price) values (542, 'Ford', 'Aerostar', 1079);
insert into cars (id, make, model, price) values (543, 'Lexus', 'GS', 1175);
insert into cars (id, make, model, price) values (544, 'Audi', 'A6', 1048);
insert into cars (id, make, model, price) values (545, 'Ford', 'Taurus X', 1061);
insert into cars (id, make, model, price) values (546, 'Acura', 'RSX', 1090);
insert into cars (id, make, model, price) values (547, 'Lexus', 'RX Hybrid', 1035);
insert into cars (id, make, model, price) values (548, 'Lexus', 'IS F', 1140);
insert into cars (id, make, model, price) values (549, 'Pontiac', 'Grand Prix', 1169);
insert into cars (id, make, model, price) values (550, 'BMW', 'X5', 1190);
insert into cars (id, make, model, price) values (551, 'Volvo', 'C70', 1130);
insert into cars (id, make, model, price) values (552, 'Ford', 'Mustang', 1196);
insert into cars (id, make, model, price) values (553, 'Lexus', 'SC', 1009);
insert into cars (id, make, model, price) values (554, 'Ford', 'F-Series', 1010);
insert into cars (id, make, model, price) values (555, 'Mitsubishi', 'Cordia', 1196);
insert into cars (id, make, model, price) values (556, 'Mercedes-Benz', 'CLS-Class', 1121);
insert into cars (id, make, model, price) values (557, 'Mitsubishi', 'Pajero', 1087);
insert into cars (id, make, model, price) values (558, 'Dodge', 'Ram 3500', 1158);
insert into cars (id, make, model, price) values (559, 'Toyota', 'Solara', 1021);
insert into cars (id, make, model, price) values (560, 'Jaguar', 'XJ Series', 1110);
insert into cars (id, make, model, price) values (561, 'MINI', 'Cooper Clubman', 1109);
insert into cars (id, make, model, price) values (562, 'Audi', 'Quattro', 1004);
insert into cars (id, make, model, price) values (563, 'Toyota', 'Tacoma', 1111);
insert into cars (id, make, model, price) values (564, 'Volkswagen', 'Cabriolet', 1088);
insert into cars (id, make, model, price) values (565, 'Ford', 'E-Series', 1141);
insert into cars (id, make, model, price) values (566, 'Chevrolet', 'Silverado 1500', 1057);
insert into cars (id, make, model, price) values (567, 'Buick', 'Regal', 1104);
insert into cars (id, make, model, price) values (568, 'Mercury', 'Grand Marquis', 1181);
insert into cars (id, make, model, price) values (569, 'Oldsmobile', 'Aurora', 1006);
insert into cars (id, make, model, price) values (570, 'Chevrolet', 'Express', 1076);
insert into cars (id, make, model, price) values (571, 'Saab', '9-3', 1102);
insert into cars (id, make, model, price) values (572, 'Nissan', 'Maxima', 1167);
insert into cars (id, make, model, price) values (573, 'Honda', 'CR-V', 1107);
insert into cars (id, make, model, price) values (574, 'Ford', 'Econoline E350', 1028);
insert into cars (id, make, model, price) values (575, 'Nissan', '350Z', 1084);
insert into cars (id, make, model, price) values (576, 'BMW', 'X5', 1194);
insert into cars (id, make, model, price) values (577, 'Plymouth', 'Colt', 1086);
insert into cars (id, make, model, price) values (578, 'BMW', '330', 1059);
insert into cars (id, make, model, price) values (579, 'Dodge', 'Shadow', 1078);
insert into cars (id, make, model, price) values (580, 'Chevrolet', 'Silverado 1500', 1096);
insert into cars (id, make, model, price) values (581, 'Oldsmobile', 'Bravada', 1021);
insert into cars (id, make, model, price) values (582, 'Chevrolet', 'Metro', 1010);
insert into cars (id, make, model, price) values (583, 'Ford', 'Escort', 1189);
insert into cars (id, make, model, price) values (584, 'Chrysler', 'Cirrus', 1114);
insert into cars (id, make, model, price) values (585, 'Lexus', 'LS', 1098);
insert into cars (id, make, model, price) values (586, 'GMC', 'Savana 1500', 1016);
insert into cars (id, make, model, price) values (587, 'Maserati', 'Spyder', 1120);
insert into cars (id, make, model, price) values (588, 'Audi', 'A4', 1064);
insert into cars (id, make, model, price) values (589, 'Mercedes-Benz', '190E', 1018);
insert into cars (id, make, model, price) values (590, 'Acura', 'TL', 1087);
insert into cars (id, make, model, price) values (591, 'Pontiac', 'Grand Prix', 1179);
insert into cars (id, make, model, price) values (592, 'Chevrolet', 'Cavalier', 1141);
insert into cars (id, make, model, price) values (593, 'Plymouth', 'Neon', 1019);
insert into cars (id, make, model, price) values (594, 'Chevrolet', 'Corvette', 1060);
insert into cars (id, make, model, price) values (595, 'Mitsubishi', 'Mighty Max', 1185);
insert into cars (id, make, model, price) values (596, 'BMW', 'X3', 1016);
insert into cars (id, make, model, price) values (597, 'Chevrolet', 'Monte Carlo', 1065);
insert into cars (id, make, model, price) values (598, 'Ford', 'E150', 1106);
insert into cars (id, make, model, price) values (599, 'Mazda', 'Mazda6', 1198);
insert into cars (id, make, model, price) values (600, 'Dodge', 'Viper', 1008);
insert into cars (id, make, model, price) values (601, 'Mercury', 'Sable', 1111);
insert into cars (id, make, model, price) values (602, 'Ford', 'Taurus', 1074);
insert into cars (id, make, model, price) values (603, 'Chevrolet', 'K5 Blazer', 1048);
insert into cars (id, make, model, price) values (604, 'Hyundai', 'Veracruz', 1020);
insert into cars (id, make, model, price) values (605, 'Pontiac', '6000', 1051);
insert into cars (id, make, model, price) values (606, 'Mercury', 'Grand Marquis', 1137);
insert into cars (id, make, model, price) values (607, 'Chevrolet', 'Caprice', 1080);
insert into cars (id, make, model, price) values (608, 'Chevrolet', 'Suburban 2500', 1137);
insert into cars (id, make, model, price) values (609, 'Chevrolet', 'G-Series 3500', 1094);
insert into cars (id, make, model, price) values (610, 'Volkswagen', 'GTI', 1196);
insert into cars (id, make, model, price) values (611, 'Land Rover', 'Discovery Series II', 1195);
insert into cars (id, make, model, price) values (612, 'Nissan', 'Xterra', 1163);
insert into cars (id, make, model, price) values (613, 'Ford', 'Aerostar', 1048);
insert into cars (id, make, model, price) values (614, 'Jeep', 'Liberty', 1005);
insert into cars (id, make, model, price) values (615, 'Toyota', 'Solara', 1157);
insert into cars (id, make, model, price) values (616, 'Maybach', 'Landaulet', 1091);
insert into cars (id, make, model, price) values (617, 'Saab', '9-5', 1024);
insert into cars (id, make, model, price) values (618, 'Lexus', 'IS', 1040);
insert into cars (id, make, model, price) values (619, 'Lotus', 'Esprit', 1171);
insert into cars (id, make, model, price) values (620, 'Chevrolet', 'Express 2500', 1119);
insert into cars (id, make, model, price) values (621, 'Chevrolet', 'Tahoe', 1109);
insert into cars (id, make, model, price) values (622, 'Mitsubishi', 'Eclipse', 1120);
insert into cars (id, make, model, price) values (623, 'Smart', 'Fortwo', 1053);
insert into cars (id, make, model, price) values (624, 'Ford', 'Ranger', 1077);
insert into cars (id, make, model, price) values (625, 'GMC', 'Canyon', 1089);
insert into cars (id, make, model, price) values (626, 'Hyundai', 'Sonata', 1115);
insert into cars (id, make, model, price) values (627, 'Mazda', '929', 1160);
insert into cars (id, make, model, price) values (628, 'Ford', 'LTD Crown Victoria', 1021);
insert into cars (id, make, model, price) values (629, 'Mitsubishi', 'Expo', 1095);
insert into cars (id, make, model, price) values (630, 'Lexus', 'IS-F', 1162);
insert into cars (id, make, model, price) values (631, 'Ford', 'Taurus', 1058);
insert into cars (id, make, model, price) values (632, 'Ford', 'E-Series', 1152);
insert into cars (id, make, model, price) values (633, 'Volkswagen', 'Passat', 1134);
insert into cars (id, make, model, price) values (634, 'Subaru', 'Brat', 1116);
insert into cars (id, make, model, price) values (635, 'Studebaker', 'Avanti', 1153);
insert into cars (id, make, model, price) values (636, 'GMC', 'Envoy XUV', 1011);
insert into cars (id, make, model, price) values (637, 'Saab', '9000', 1138);
insert into cars (id, make, model, price) values (638, 'Lincoln', 'Mark VIII', 1195);
insert into cars (id, make, model, price) values (639, 'Mazda', 'Miata MX-5', 1033);
insert into cars (id, make, model, price) values (640, 'Buick', 'Lucerne', 1061);
insert into cars (id, make, model, price) values (641, 'Pontiac', 'Grand Am', 1056);
insert into cars (id, make, model, price) values (642, 'Nissan', 'Quest', 1116);
insert into cars (id, make, model, price) values (643, 'Mercury', 'Villager', 1058);
insert into cars (id, make, model, price) values (644, 'Ford', 'Fiesta', 1081);
insert into cars (id, make, model, price) values (645, 'GMC', 'Savana 2500', 1000);
insert into cars (id, make, model, price) values (646, 'Mercury', 'Sable', 1100);
insert into cars (id, make, model, price) values (647, 'Dodge', 'Caravan', 1005);
insert into cars (id, make, model, price) values (648, 'Lincoln', 'Blackwood', 1077);
insert into cars (id, make, model, price) values (649, 'Volkswagen', 'Rabbit', 1126);
insert into cars (id, make, model, price) values (650, 'Kia', 'Sorento', 1007);
insert into cars (id, make, model, price) values (651, 'Ford', 'F350', 1136);
insert into cars (id, make, model, price) values (652, 'Hyundai', 'Veloster', 1073);
insert into cars (id, make, model, price) values (653, 'Chevrolet', 'Camaro', 1002);
insert into cars (id, make, model, price) values (654, 'Toyota', 'Corolla', 1109);
insert into cars (id, make, model, price) values (655, 'Ford', 'F250', 1076);
insert into cars (id, make, model, price) values (656, 'Suzuki', 'Sidekick', 1163);
insert into cars (id, make, model, price) values (657, 'Isuzu', 'Trooper', 1175);
insert into cars (id, make, model, price) values (658, 'Toyota', 'Sequoia', 1155);
insert into cars (id, make, model, price) values (659, 'Mitsubishi', 'Eclipse', 1155);
insert into cars (id, make, model, price) values (660, 'Lotus', 'Exige', 1172);
insert into cars (id, make, model, price) values (661, 'Fillmore', 'Fillmore', 1013);
insert into cars (id, make, model, price) values (662, 'Chevrolet', 'Silverado', 1134);
insert into cars (id, make, model, price) values (663, 'Dodge', 'Grand Caravan', 1115);
insert into cars (id, make, model, price) values (664, 'Chevrolet', 'Suburban 1500', 1133);
insert into cars (id, make, model, price) values (665, 'Isuzu', 'Trooper', 1182);
insert into cars (id, make, model, price) values (666, 'Nissan', 'Sentra', 1159);
insert into cars (id, make, model, price) values (667, 'Pontiac', 'Sunbird', 1089);
insert into cars (id, make, model, price) values (668, 'Dodge', 'Dakota', 1181);
insert into cars (id, make, model, price) values (669, 'Subaru', 'Forester', 1066);
insert into cars (id, make, model, price) values (670, 'Honda', 'Accord', 1117);
insert into cars (id, make, model, price) values (671, 'Ford', 'Aerostar', 1061);
insert into cars (id, make, model, price) values (672, 'Lotus', 'Elan', 1108);
insert into cars (id, make, model, price) values (673, 'Aston Martin', 'V8 Vantage', 1070);
insert into cars (id, make, model, price) values (674, 'Mercedes-Benz', 'GL-Class', 1186);
insert into cars (id, make, model, price) values (675, 'Isuzu', 'Amigo', 1170);
insert into cars (id, make, model, price) values (676, 'Ford', 'E350', 1131);
insert into cars (id, make, model, price) values (677, 'Chevrolet', 'Cavalier', 1153);
insert into cars (id, make, model, price) values (678, 'Dodge', 'Stratus', 1067);
insert into cars (id, make, model, price) values (679, 'Jaguar', 'XF', 1171);
insert into cars (id, make, model, price) values (680, 'Ford', 'Aerostar', 1182);
insert into cars (id, make, model, price) values (681, 'GMC', 'Suburban 2500', 1040);
insert into cars (id, make, model, price) values (682, 'Land Rover', 'Range Rover Sport', 1091);
insert into cars (id, make, model, price) values (683, 'Dodge', 'Caravan', 1023);
insert into cars (id, make, model, price) values (684, 'Lamborghini', 'Diablo', 1170);
insert into cars (id, make, model, price) values (685, 'Dodge', 'Intrepid', 1103);
insert into cars (id, make, model, price) values (686, 'Isuzu', 'Amigo', 1009);
insert into cars (id, make, model, price) values (687, 'Chevrolet', 'Express 1500', 1111);
insert into cars (id, make, model, price) values (688, 'Audi', 'Cabriolet', 1099);
insert into cars (id, make, model, price) values (689, 'Dodge', 'Neon', 1173);
insert into cars (id, make, model, price) values (690, 'Chevrolet', 'Cobalt', 1198);
insert into cars (id, make, model, price) values (691, 'Saturn', 'S-Series', 1076);
insert into cars (id, make, model, price) values (692, 'Chrysler', 'LHS', 1194);
insert into cars (id, make, model, price) values (693, 'Rolls-Royce', 'Phantom', 1068);
insert into cars (id, make, model, price) values (694, 'Mazda', 'MX-5', 1018);
insert into cars (id, make, model, price) values (695, 'Chevrolet', 'Sportvan G30', 1119);
insert into cars (id, make, model, price) values (696, 'Dodge', 'Dakota Club', 1065);
insert into cars (id, make, model, price) values (697, 'Toyota', 'Xtra', 1198);
insert into cars (id, make, model, price) values (698, 'Subaru', 'Forester', 1188);
insert into cars (id, make, model, price) values (699, 'Chevrolet', 'Express', 1145);
insert into cars (id, make, model, price) values (700, 'Cadillac', 'XLR', 1130);
insert into cars (id, make, model, price) values (701, 'Hyundai', 'Veloster', 1086);
insert into cars (id, make, model, price) values (702, 'Porsche', 'Cayenne', 1163);
insert into cars (id, make, model, price) values (703, 'Acura', 'Integra', 1159);
insert into cars (id, make, model, price) values (704, 'Ford', 'Ranger', 1117);
insert into cars (id, make, model, price) values (705, 'Ford', 'Expedition EL', 1182);
insert into cars (id, make, model, price) values (706, 'Ford', 'Flex', 1190);
insert into cars (id, make, model, price) values (707, 'Acura', 'Integra', 1110);
insert into cars (id, make, model, price) values (708, 'Lincoln', 'LS', 1179);
insert into cars (id, make, model, price) values (709, 'Chevrolet', 'Tahoe', 1035);
insert into cars (id, make, model, price) values (710, 'Toyota', 'Camry', 1155);
insert into cars (id, make, model, price) values (711, 'Audi', 'S6', 1027);
insert into cars (id, make, model, price) values (712, 'Chrysler', 'Town & Country', 1137);
insert into cars (id, make, model, price) values (713, 'Suzuki', 'XL-7', 1147);
insert into cars (id, make, model, price) values (714, 'Ford', 'Explorer Sport Trac', 1182);
insert into cars (id, make, model, price) values (715, 'Dodge', 'Durango', 1118);
insert into cars (id, make, model, price) values (716, 'Mazda', 'Mazdaspeed 3', 1083);
insert into cars (id, make, model, price) values (717, 'Hyundai', 'Elantra', 1028);
insert into cars (id, make, model, price) values (718, 'Ford', 'Flex', 1094);
insert into cars (id, make, model, price) values (719, 'GMC', '3500', 1114);
insert into cars (id, make, model, price) values (720, 'Mercedes-Benz', 'GLK-Class', 1049);
insert into cars (id, make, model, price) values (721, 'Dodge', 'Challenger', 1162);
insert into cars (id, make, model, price) values (722, 'Ford', 'Escort', 1156);
insert into cars (id, make, model, price) values (723, 'Volvo', 'S40', 1048);
insert into cars (id, make, model, price) values (724, 'Mercedes-Benz', 'SLK-Class', 1005);
insert into cars (id, make, model, price) values (725, 'Honda', 'Civic', 1066);
insert into cars (id, make, model, price) values (726, 'GMC', 'Sierra 2500', 1072);
insert into cars (id, make, model, price) values (727, 'Acura', 'NSX', 1192);
insert into cars (id, make, model, price) values (728, 'Volvo', 'S40', 1072);
insert into cars (id, make, model, price) values (729, 'Mercedes-Benz', 'W123', 1200);
insert into cars (id, make, model, price) values (730, 'Honda', 'CR-V', 1080);
insert into cars (id, make, model, price) values (731, 'BMW', 'X5', 1058);
insert into cars (id, make, model, price) values (732, 'Bentley', 'Continental GTC', 1105);
insert into cars (id, make, model, price) values (733, 'Suzuki', 'Swift', 1189);
insert into cars (id, make, model, price) values (734, 'Ford', 'Expedition', 1120);
insert into cars (id, make, model, price) values (735, 'Saab', '9000', 1100);
insert into cars (id, make, model, price) values (736, 'Suzuki', 'XL7', 1119);
insert into cars (id, make, model, price) values (737, 'Ferrari', '458 Italia', 1067);
insert into cars (id, make, model, price) values (738, 'Isuzu', 'Rodeo Sport', 1138);
insert into cars (id, make, model, price) values (739, 'Plymouth', 'Colt', 1088);
insert into cars (id, make, model, price) values (740, 'Honda', 'Accord', 1033);
insert into cars (id, make, model, price) values (741, 'Ford', 'Tempo', 1035);
insert into cars (id, make, model, price) values (742, 'Toyota', 'Avalon', 1135);
insert into cars (id, make, model, price) values (743, 'Maybach', '62', 1016);
insert into cars (id, make, model, price) values (744, 'BMW', 'X6 M', 1106);
insert into cars (id, make, model, price) values (745, 'Mitsubishi', 'Montero', 1129);
insert into cars (id, make, model, price) values (746, 'Mazda', 'CX-5', 1043);
insert into cars (id, make, model, price) values (747, 'Ford', 'E350', 1086);
insert into cars (id, make, model, price) values (748, 'Ford', 'Contour', 1160);
insert into cars (id, make, model, price) values (749, 'Land Rover', 'Range Rover', 1143);
insert into cars (id, make, model, price) values (750, 'Jaguar', 'XJ', 1058);
insert into cars (id, make, model, price) values (751, 'Lexus', 'RX Hybrid', 1029);
insert into cars (id, make, model, price) values (752, 'Buick', 'Lucerne', 1175);
insert into cars (id, make, model, price) values (753, 'Chrysler', '300', 1030);
insert into cars (id, make, model, price) values (754, 'Mitsubishi', 'Lancer', 1111);
insert into cars (id, make, model, price) values (755, 'Lexus', 'IS', 1004);
insert into cars (id, make, model, price) values (756, 'Ford', 'Escort', 1139);
insert into cars (id, make, model, price) values (757, 'Chevrolet', 'Malibu', 1187);
insert into cars (id, make, model, price) values (758, 'Audi', 'Quattro', 1198);
insert into cars (id, make, model, price) values (759, 'Audi', 'S6', 1111);
insert into cars (id, make, model, price) values (760, 'Nissan', '200SX', 1196);
insert into cars (id, make, model, price) values (761, 'Porsche', '911', 1138);
insert into cars (id, make, model, price) values (762, 'Chevrolet', 'Tahoe', 1029);
insert into cars (id, make, model, price) values (763, 'Volkswagen', 'GTI', 1019);
insert into cars (id, make, model, price) values (764, 'Alfa Romeo', 'Spider', 1023);
insert into cars (id, make, model, price) values (765, 'Chevrolet', '1500', 1150);
insert into cars (id, make, model, price) values (766, 'Mercury', 'Mystique', 1087);
insert into cars (id, make, model, price) values (767, 'Isuzu', 'Space', 1111);
insert into cars (id, make, model, price) values (768, 'Chevrolet', 'Impala', 1162);
insert into cars (id, make, model, price) values (769, 'Hyundai', 'Accent', 1102);
insert into cars (id, make, model, price) values (770, 'Chevrolet', 'S10', 1050);
insert into cars (id, make, model, price) values (771, 'Volvo', 'S40', 1148);
insert into cars (id, make, model, price) values (772, 'Mercedes-Benz', 'SLK55 AMG', 1164);
insert into cars (id, make, model, price) values (773, 'Audi', 'A4', 1095);
insert into cars (id, make, model, price) values (774, 'Saturn', 'VUE', 1042);
insert into cars (id, make, model, price) values (775, 'Chevrolet', 'Corvette', 1069);
insert into cars (id, make, model, price) values (776, 'Ford', 'Explorer', 1112);
insert into cars (id, make, model, price) values (777, 'Dodge', 'Ram Van 2500', 1029);
insert into cars (id, make, model, price) values (778, 'Chevrolet', 'Express 3500', 1134);
insert into cars (id, make, model, price) values (779, 'Ford', 'F450', 1128);
insert into cars (id, make, model, price) values (780, 'Lexus', 'ES', 1153);
insert into cars (id, make, model, price) values (781, 'Aston Martin', 'Vantage', 1103);
insert into cars (id, make, model, price) values (782, 'Dodge', 'Ram Van 3500', 1139);
insert into cars (id, make, model, price) values (783, 'Chevrolet', '1500', 1027);
insert into cars (id, make, model, price) values (784, 'Audi', 'R8', 1029);
insert into cars (id, make, model, price) values (785, 'Pontiac', 'Bonneville', 1146);
insert into cars (id, make, model, price) values (786, 'Land Rover', 'Discovery Series II', 1169);
insert into cars (id, make, model, price) values (787, 'Land Rover', 'Range Rover', 1150);
insert into cars (id, make, model, price) values (788, 'Rolls-Royce', 'Phantom', 1031);
insert into cars (id, make, model, price) values (789, 'Cadillac', 'Escalade ESV', 1154);
insert into cars (id, make, model, price) values (790, 'Jaguar', 'XJ Series', 1088);
insert into cars (id, make, model, price) values (791, 'Chrysler', 'LeBaron', 1177);
insert into cars (id, make, model, price) values (792, 'GMC', 'Sierra Hybrid', 1072);
insert into cars (id, make, model, price) values (793, 'Pontiac', 'Firefly', 1132);
insert into cars (id, make, model, price) values (794, 'Toyota', 'Camry', 1125);
insert into cars (id, make, model, price) values (795, 'Saturn', 'VUE', 1062);
insert into cars (id, make, model, price) values (796, 'Audi', 'S4', 1001);
insert into cars (id, make, model, price) values (797, 'Mercury', 'Capri', 1025);
insert into cars (id, make, model, price) values (798, 'Toyota', 'Avalon', 1006);
insert into cars (id, make, model, price) values (799, 'Pontiac', 'Grand Am', 1149);
insert into cars (id, make, model, price) values (800, 'Chevrolet', 'Caprice', 1015);
insert into cars (id, make, model, price) values (801, 'Hyundai', 'Santa Fe', 1050);
insert into cars (id, make, model, price) values (802, 'Volvo', 'C70', 1023);
insert into cars (id, make, model, price) values (803, 'Toyota', 'Sequoia', 1121);
insert into cars (id, make, model, price) values (804, 'Jeep', 'Grand Cherokee', 1116);
insert into cars (id, make, model, price) values (805, 'Mazda', '929', 1066);
insert into cars (id, make, model, price) values (806, 'Mazda', 'Mazda6', 1196);
insert into cars (id, make, model, price) values (807, 'Cadillac', 'Escalade EXT', 1024);
insert into cars (id, make, model, price) values (808, 'Mercury', 'Sable', 1096);
insert into cars (id, make, model, price) values (809, 'Mercedes-Benz', 'W201', 1067);
insert into cars (id, make, model, price) values (810, 'GMC', 'Savana 1500', 1125);
insert into cars (id, make, model, price) values (811, 'Lincoln', 'Navigator', 1019);
insert into cars (id, make, model, price) values (812, 'Saturn', 'L-Series', 1020);
insert into cars (id, make, model, price) values (813, 'Chevrolet', 'Astro', 1119);
insert into cars (id, make, model, price) values (814, 'Nissan', 'Altima', 1161);
insert into cars (id, make, model, price) values (815, 'Bentley', 'Continental', 1028);
insert into cars (id, make, model, price) values (816, 'Spyker', 'C8 Spyder', 1130);
insert into cars (id, make, model, price) values (817, 'Lamborghini', 'Reventón', 1144);
insert into cars (id, make, model, price) values (818, 'Plymouth', 'Roadrunner', 1123);
insert into cars (id, make, model, price) values (819, 'Mercury', 'Grand Marquis', 1074);
insert into cars (id, make, model, price) values (820, 'Chevrolet', 'Metro', 1061);
insert into cars (id, make, model, price) values (821, 'Chevrolet', 'Prizm', 1187);
insert into cars (id, make, model, price) values (822, 'Rambler', 'Classic', 1024);
insert into cars (id, make, model, price) values (823, 'Nissan', 'Quest', 1037);
insert into cars (id, make, model, price) values (824, 'Audi', '90', 1057);
insert into cars (id, make, model, price) values (825, 'GMC', 'Jimmy', 1050);
insert into cars (id, make, model, price) values (826, 'Mercedes-Benz', 'W201', 1118);
insert into cars (id, make, model, price) values (827, 'Dodge', 'Avenger', 1166);
insert into cars (id, make, model, price) values (828, 'Cadillac', 'Allante', 1097);
insert into cars (id, make, model, price) values (829, 'Maserati', 'Quattroporte', 1077);
insert into cars (id, make, model, price) values (830, 'Infiniti', 'I', 1129);
insert into cars (id, make, model, price) values (831, 'Mitsubishi', 'Mighty Max', 1041);
insert into cars (id, make, model, price) values (832, 'Chevrolet', 'Express', 1122);
insert into cars (id, make, model, price) values (833, 'Dodge', 'Charger', 1026);
insert into cars (id, make, model, price) values (834, 'Hummer', 'H1', 1093);
insert into cars (id, make, model, price) values (835, 'Jaguar', 'XF', 1182);
insert into cars (id, make, model, price) values (836, 'Mercedes-Benz', 'SL-Class', 1035);
insert into cars (id, make, model, price) values (837, 'Buick', 'LeSabre', 1184);
insert into cars (id, make, model, price) values (838, 'Chevrolet', 'Colorado', 1024);
insert into cars (id, make, model, price) values (839, 'Dodge', 'Grand Caravan', 1095);
insert into cars (id, make, model, price) values (840, 'Cadillac', 'CTS', 1167);
insert into cars (id, make, model, price) values (841, 'Ford', 'Taurus', 1189);
insert into cars (id, make, model, price) values (842, 'Toyota', 'Matrix', 1024);
insert into cars (id, make, model, price) values (843, 'Chevrolet', 'Corvette', 1130);
insert into cars (id, make, model, price) values (844, 'Ford', 'Contour', 1059);
insert into cars (id, make, model, price) values (845, 'Saturn', 'Ion', 1085);
insert into cars (id, make, model, price) values (846, 'Ferrari', '599 GTB Fiorano', 1123);
insert into cars (id, make, model, price) values (847, 'Oldsmobile', '98', 1086);
insert into cars (id, make, model, price) values (848, 'Ford', 'Mustang', 1030);
insert into cars (id, make, model, price) values (849, 'Ford', 'Thunderbird', 1162);
insert into cars (id, make, model, price) values (850, 'BMW', 'X6 M', 1198);
insert into cars (id, make, model, price) values (851, 'Volkswagen', 'Golf', 1110);
insert into cars (id, make, model, price) values (852, 'Maserati', 'Spyder', 1174);
insert into cars (id, make, model, price) values (853, 'Acura', 'RSX', 1018);
insert into cars (id, make, model, price) values (854, 'Dodge', 'Ram', 1021);
insert into cars (id, make, model, price) values (855, 'Buick', 'Regal', 1097);
insert into cars (id, make, model, price) values (856, 'Chevrolet', 'Lumina', 1071);
insert into cars (id, make, model, price) values (857, 'Mercury', 'Topaz', 1021);
insert into cars (id, make, model, price) values (858, 'GMC', 'Safari', 1193);
insert into cars (id, make, model, price) values (859, 'Buick', 'Electra', 1013);
insert into cars (id, make, model, price) values (860, 'Mitsubishi', 'Truck', 1114);
insert into cars (id, make, model, price) values (861, 'Buick', 'Electra', 1109);
insert into cars (id, make, model, price) values (862, 'Ford', 'Econoline E350', 1031);
insert into cars (id, make, model, price) values (863, 'Austin', 'Mini Cooper', 1024);
insert into cars (id, make, model, price) values (864, 'Lexus', 'RX', 1024);
insert into cars (id, make, model, price) values (865, 'GMC', 'Sonoma Club', 1066);
insert into cars (id, make, model, price) values (866, 'Maybach', '57', 1083);
insert into cars (id, make, model, price) values (867, 'Volvo', '960', 1045);
insert into cars (id, make, model, price) values (868, 'Mitsubishi', 'Endeavor', 1190);
insert into cars (id, make, model, price) values (869, 'Honda', 'Prelude', 1041);
insert into cars (id, make, model, price) values (870, 'Pontiac', 'Grand Prix', 1027);
insert into cars (id, make, model, price) values (871, 'Infiniti', 'IPL G', 1072);
insert into cars (id, make, model, price) values (872, 'Dodge', 'Ram 3500', 1109);
insert into cars (id, make, model, price) values (873, 'Chrysler', 'Town & Country', 1140);
insert into cars (id, make, model, price) values (874, 'Pontiac', 'Tempest', 1137);
insert into cars (id, make, model, price) values (875, 'Mitsubishi', 'Eclipse', 1009);
insert into cars (id, make, model, price) values (876, 'Chevrolet', 'Sportvan G30', 1074);
insert into cars (id, make, model, price) values (877, 'Ford', 'Expedition', 1077);
insert into cars (id, make, model, price) values (878, 'Toyota', 'Highlander', 1110);
insert into cars (id, make, model, price) values (879, 'Chevrolet', 'Express', 1028);
insert into cars (id, make, model, price) values (880, 'GMC', 'Savana 1500', 1006);
insert into cars (id, make, model, price) values (881, 'Mazda', 'Familia', 1099);
insert into cars (id, make, model, price) values (882, 'Ram', '3500', 1127);
insert into cars (id, make, model, price) values (883, 'Ford', 'Crown Victoria', 1123);
insert into cars (id, make, model, price) values (884, 'Volkswagen', 'Golf', 1165);
insert into cars (id, make, model, price) values (885, 'Lincoln', 'Continental Mark VII', 1163);
insert into cars (id, make, model, price) values (886, 'Toyota', 'Sequoia', 1006);
insert into cars (id, make, model, price) values (887, 'Mazda', 'MX-5', 1051);
insert into cars (id, make, model, price) values (888, 'Toyota', 'Sienna', 1106);
insert into cars (id, make, model, price) values (889, 'Subaru', 'Forester', 1026);
insert into cars (id, make, model, price) values (890, 'Isuzu', 'Rodeo', 1190);
insert into cars (id, make, model, price) values (891, 'Ford', 'E350', 1192);
insert into cars (id, make, model, price) values (892, 'Chevrolet', 'Cavalier', 1155);
insert into cars (id, make, model, price) values (893, 'Lexus', 'RX', 1092);
insert into cars (id, make, model, price) values (894, 'Chevrolet', 'Camaro', 1009);
insert into cars (id, make, model, price) values (895, 'Mitsubishi', 'Expo', 1139);
insert into cars (id, make, model, price) values (896, 'Mazda', 'Mazda6 Sport', 1153);
insert into cars (id, make, model, price) values (897, 'Honda', 'Insight', 1051);
insert into cars (id, make, model, price) values (898, 'Dodge', 'Caravan', 1026);
insert into cars (id, make, model, price) values (899, 'Infiniti', 'Q', 1147);
insert into cars (id, make, model, price) values (900, 'Buick', 'Park Avenue', 1011);
insert into cars (id, make, model, price) values (901, 'Mazda', 'Mazda5', 1128);
insert into cars (id, make, model, price) values (902, 'Dodge', 'Ram Van 3500', 1088);
insert into cars (id, make, model, price) values (903, 'Mercedes-Benz', 'S-Class', 1077);
insert into cars (id, make, model, price) values (904, 'Chevrolet', 'Traverse', 1013);
insert into cars (id, make, model, price) values (905, 'Toyota', 'T100', 1045);
insert into cars (id, make, model, price) values (906, 'Chevrolet', 'Monte Carlo', 1133);
insert into cars (id, make, model, price) values (907, 'Volvo', 'V70', 1172);
insert into cars (id, make, model, price) values (908, 'Subaru', 'Legacy', 1178);
insert into cars (id, make, model, price) values (909, 'Suzuki', 'XL7', 1188);
insert into cars (id, make, model, price) values (910, 'Ford', 'EXP', 1066);
insert into cars (id, make, model, price) values (911, 'Volkswagen', 'Fox', 1090);
insert into cars (id, make, model, price) values (912, 'Honda', 'S2000', 1035);
insert into cars (id, make, model, price) values (913, 'Mercedes-Benz', 'E-Class', 1074);
insert into cars (id, make, model, price) values (914, 'Audi', 'Quattro', 1124);
insert into cars (id, make, model, price) values (915, 'Lexus', 'LS', 1064);
insert into cars (id, make, model, price) values (916, 'Ford', 'F-Series', 1100);
insert into cars (id, make, model, price) values (917, 'Ford', 'LTD', 1023);
insert into cars (id, make, model, price) values (918, 'Mercedes-Benz', 'Sprinter 2500', 1174);
insert into cars (id, make, model, price) values (919, 'Dodge', 'Nitro', 1189);
insert into cars (id, make, model, price) values (920, 'Hyundai', 'Accent', 1117);
insert into cars (id, make, model, price) values (921, 'GMC', 'Savana 1500', 1063);
insert into cars (id, make, model, price) values (922, 'Chevrolet', 'Monte Carlo', 1087);
insert into cars (id, make, model, price) values (923, 'Porsche', '911', 1000);
insert into cars (id, make, model, price) values (924, 'Dodge', 'Ram Van 3500', 1106);
insert into cars (id, make, model, price) values (925, 'Infiniti', 'QX', 1011);
insert into cars (id, make, model, price) values (926, 'Cadillac', 'STS-V', 1040);
insert into cars (id, make, model, price) values (927, 'Lincoln', 'Continental', 1062);
insert into cars (id, make, model, price) values (928, 'BMW', '7 Series', 1031);
insert into cars (id, make, model, price) values (929, 'Isuzu', 'Amigo', 1106);
insert into cars (id, make, model, price) values (930, 'Volvo', 'S40', 1149);
insert into cars (id, make, model, price) values (931, 'Kia', 'Spectra', 1188);
insert into cars (id, make, model, price) values (932, 'Ford', 'Tempo', 1055);
insert into cars (id, make, model, price) values (933, 'Kia', 'Rondo', 1013);
insert into cars (id, make, model, price) values (934, 'Chevrolet', 'Prizm', 1109);
insert into cars (id, make, model, price) values (935, 'Chrysler', 'Town & Country', 1185);
insert into cars (id, make, model, price) values (936, 'GMC', 'Yukon', 1029);
insert into cars (id, make, model, price) values (937, 'Mitsubishi', 'Raider', 1118);
insert into cars (id, make, model, price) values (938, 'Mitsubishi', 'Chariot', 1034);
insert into cars (id, make, model, price) values (939, 'Mitsubishi', 'Mighty Max', 1145);
insert into cars (id, make, model, price) values (940, 'Chevrolet', 'Equinox', 1189);
insert into cars (id, make, model, price) values (941, 'Jaguar', 'XJ Series', 1126);
insert into cars (id, make, model, price) values (942, 'Infiniti', 'I', 1126);
insert into cars (id, make, model, price) values (943, 'Mercedes-Benz', 'SL-Class', 1003);
insert into cars (id, make, model, price) values (944, 'Ford', 'E-Series', 1126);
insert into cars (id, make, model, price) values (945, 'Suzuki', 'X-90', 1066);
insert into cars (id, make, model, price) values (946, 'Lamborghini', 'Reventón', 1172);
insert into cars (id, make, model, price) values (947, 'Volvo', 'S80', 1023);
insert into cars (id, make, model, price) values (948, 'Mercedes-Benz', 'E-Class', 1135);
insert into cars (id, make, model, price) values (949, 'Hyundai', 'Sonata', 1089);
insert into cars (id, make, model, price) values (950, 'Oldsmobile', 'Custom Cruiser', 1171);
insert into cars (id, make, model, price) values (951, 'Dodge', 'Ram Van B350', 1139);
insert into cars (id, make, model, price) values (952, 'Mercedes-Benz', 'SL-Class', 1151);
insert into cars (id, make, model, price) values (953, 'BMW', 'M3', 1117);
insert into cars (id, make, model, price) values (954, 'Mitsubishi', 'Diamante', 1183);
insert into cars (id, make, model, price) values (955, 'Mercury', 'Montego', 1135);
insert into cars (id, make, model, price) values (956, 'Lincoln', 'MKZ', 1137);
insert into cars (id, make, model, price) values (957, 'Toyota', 'Tundra', 1110);
insert into cars (id, make, model, price) values (958, 'Oldsmobile', 'LSS', 1016);
insert into cars (id, make, model, price) values (959, 'Dodge', 'Dakota', 1171);
insert into cars (id, make, model, price) values (960, 'Mitsubishi', 'Precis', 1055);
insert into cars (id, make, model, price) values (961, 'Ford', 'F350', 1198);
insert into cars (id, make, model, price) values (962, 'Chrysler', 'LHS', 1143);
insert into cars (id, make, model, price) values (963, 'Nissan', 'Sentra', 1067);
insert into cars (id, make, model, price) values (964, 'Porsche', '911', 1111);
insert into cars (id, make, model, price) values (965, 'Acura', 'NSX', 1096);
insert into cars (id, make, model, price) values (966, 'Volkswagen', 'Golf', 1134);
insert into cars (id, make, model, price) values (967, 'Lexus', 'ES', 1108);
insert into cars (id, make, model, price) values (968, 'GMC', '3500 Club Coupe', 1054);
insert into cars (id, make, model, price) values (969, 'Honda', 'CR-V', 1170);
insert into cars (id, make, model, price) values (970, 'Pontiac', 'LeMans', 1168);
insert into cars (id, make, model, price) values (971, 'Chevrolet', 'Traverse', 1007);
insert into cars (id, make, model, price) values (972, 'Buick', 'Roadmaster', 1094);
insert into cars (id, make, model, price) values (973, 'Mercury', 'Cougar', 1050);
insert into cars (id, make, model, price) values (974, 'Chrysler', 'Concorde', 1001);
insert into cars (id, make, model, price) values (975, 'Cadillac', 'Seville', 1123);
insert into cars (id, make, model, price) values (976, 'Land Rover', 'Range Rover', 1095);
insert into cars (id, make, model, price) values (977, 'Volkswagen', 'Scirocco', 1001);
insert into cars (id, make, model, price) values (978, 'Chevrolet', 'Suburban 1500', 1025);
insert into cars (id, make, model, price) values (979, 'Infiniti', 'G', 1010);
insert into cars (id, make, model, price) values (980, 'Mercedes-Benz', 'C-Class', 1047);
insert into cars (id, make, model, price) values (981, 'Toyota', 'Previa', 1055);
insert into cars (id, make, model, price) values (982, 'Buick', 'Estate', 1153);
insert into cars (id, make, model, price) values (983, 'Buick', 'LeSabre', 1057);
insert into cars (id, make, model, price) values (984, 'Nissan', 'Maxima', 1137);
insert into cars (id, make, model, price) values (985, 'Oldsmobile', 'Achieva', 1061);
insert into cars (id, make, model, price) values (986, 'Toyota', 'Corolla', 1042);
insert into cars (id, make, model, price) values (987, 'Kia', 'Rio', 1196);
insert into cars (id, make, model, price) values (988, 'BMW', 'X6 M', 1028);
insert into cars (id, make, model, price) values (989, 'Mazda', 'Navajo', 1037);
insert into cars (id, make, model, price) values (990, 'Chevrolet', 'Silverado 3500', 1167);
insert into cars (id, make, model, price) values (991, 'Suzuki', 'X-90', 1027);
insert into cars (id, make, model, price) values (992, 'Audi', 'S5', 1085);
insert into cars (id, make, model, price) values (993, 'Aston Martin', 'V8 Vantage', 1088);
insert into cars (id, make, model, price) values (994, 'Mitsubishi', 'Expo', 1066);
insert into cars (id, make, model, price) values (995, 'Pontiac', 'GTO', 1096);
insert into cars (id, make, model, price) values (996, 'Mitsubishi', 'Lancer', 1111);
insert into cars (id, make, model, price) values (997, 'Ford', 'Mustang', 1183);
insert into cars (id, make, model, price) values (998, 'Hyundai', 'Accent', 1175);
insert into cars (id, make, model, price) values (999, 'Ford', 'F350', 1124);
insert into cars (id, make, model, price) values (1000, 'Chevrolet', 'Camaro', 1013);
